<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dev.sivalabs</groupId>
    <artifactId>spring-io-2026-intellijidea-workshop</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>spring-io-2026-intellijidea-workshop</name>
    <description>Spring I/O 2026 IntelliJ IDEA Workshop</description>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <maven.compiler.release>25</maven.compiler.release>
    </properties>

    <modules>
        <module>bookstore</module>
        <module>bookstore-modulith-wip</module>
        <module>bookstore-modulith</module>
    </modules>

</project>
