services:
  postgres:
    image: 'postgres:18-alpine'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  mailpit:
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025"
      - "8025:8025"

  springio-2026-demo:
    image: sivaprasadreddy/springio-2026-demo
    container_name: springio-2026-demo
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EMAIL_HOST: mailpit
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - app
