spring.application.name=bookstore-modulith

#### App Config ####
app.support-email=siva@sivalabs.com
app.orders-per-page=5
app.email-service-type=javamail
#### Database Config ####
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
spring.jpa.show-sql=false

#### Actuator Config ######
management.endpoints.web.exposure.include=info,health
management.endpoint.health.probes.enabled=true

################### JavaMail Configuration ##########################
spring.mail.host=${EMAIL_HOST:127.0.0.1}
spring.mail.port=${EMAIL_PORT:1025}
spring.mail.protocol=smtp
spring.mail.username=siva@sivalabs.com
spring.mail.password=secret
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=2000
